defmodule Ichor.ABNF do
  @moduledoc """
  The ABNF (RFC 5234 + RFC 7405) front-end: `priv/grammar/abnf.aether`
  parsed by Aether's own front-end, compiled by the native codegen
  backend (`use Ichor`), dispatching to `Ichor.ABNF.Actions`
  (`Grammar.IR` as its target category, same as `Regex.Actions`).

  The `.aether` source lives under `priv/grammar/`, not `lib/`, since
  `use Ichor` only ever reads it once, at compile time, to generate this
  module's own functions -- nothing about it is needed once the BEAM
  file exists, so it's a build-time asset (`priv/`'s own purpose),
  not a runtime one.

      iex> {:ok, ruleset} = Ichor.ABNF.run("ip4-octet = 1*3DIGIT\\r\\n")
      iex> ruleset[:"ip4-octet"]
      %Grammar.IR.Rep{expr: %Grammar.IR.RuleRef{name: :digit}, min: 1, max: 3}

  `run/1` (generated by `use Ichor`) returns `{:ok, %{rule_name_atom =>
  Grammar.IR.expr()}}` for a whole `rulelist` -- every rule the source
  defines, keyed by its (lowercased, per RFC 5234) name. `parse/1` and
  `tokenize/1` (also generated) are available for a bare recognizer or
  raw token stream, with no `Ichor.ABNF.Actions` involved.
  """

  use Ichor,
    grammar: "../../priv/grammar/abnf.aether",
    actions: Ichor.ABNF.Actions
end
