defmodule Ichor.BNF do
  @moduledoc """
  The classical BNF front-end -- no single citable standard exists;
  this follows the ALGOL 60 Report's own convention with quoted
  terminals, matching how BNF is actually written today (see
  `Ichor.BNF.Actions`'s own moduledoc for the deliberate deviation that
  is): `priv/grammar/bnf.aether` parsed by Aether's own front-end,
  compiled by the native codegen backend (`use Ichor`), dispatching to
  `Ichor.BNF.Actions` (`Grammar.IR` as its target category).

  The `.aether` source lives under `priv/grammar/`, not `lib/`, for the
  same reason as `Ichor.ABNF`'s own: `use Ichor` only ever reads it once,
  at compile time.

      iex> {:ok, ruleset} = Ichor.BNF.run("<digit> ::= '0' | '1'\\n")
      iex> ruleset[:digit]
      %Grammar.IR.Choice{exprs: [%Grammar.IR.Literal{value: "0"}, %Grammar.IR.Literal{value: "1"}]}

  `run/1` (generated by `use Ichor`) returns `{:ok, %{nonterminal_name_atom
  => Grammar.IR.expr()}}` for a whole `grammar_file` -- every rule the
  source defines, keyed by its nonterminal name exactly as written
  (classical BNF has no case-insensitivity rule the way ABNF does).
  `parse/1` and `tokenize/1` (also generated) are available for a bare
  recognizer or raw token stream, with no `Ichor.BNF.Actions` involved.
  """

  use Ichor,
    grammar: "../../priv/grammar/bnf.aether",
    actions: Ichor.BNF.Actions
end
