defmodule Ichor.GrammarImport do
  @moduledoc """
  Turns an ABNF/BNF/ISO-EBNF/PEG ruleset (as `Ichor.ABNF`/`Ichor.BNF`/
  `Ichor.EBNF.ISO`/`Ichor.PEG` produce them -- `%{rule_name_atom =>
  Grammar.IR.expr()}`, explicitly documented as "not a runnable
  `Aether.Grammar`") into one that actually is: picks a root (the
  source's own first-declared rule, unless overridden), assembles a
  full `%Aether.Grammar{}`, and (for ABNF specifically) fills in RFC
  5234 Appendix B's implicit "core rules" (`ALPHA`, `DIGIT`, `CRLF`,
  ...) for anything the source references but never defines itself --
  extremely common in real ABNF, which generally assumes those are
  always available.

  `Mix.Tasks.Ichor.Gen`'s own entry point for a grammar whose source
  isn't `.aether` text at all; nothing here is native-Aether-specific,
  so it's equally usable standalone by anything else that wants a
  runnable grammar out of one of these formats.

  None of ABNF, ISO EBNF, or PEG (as specified, and as this project's
  own importers implement them) have Aether's own named-capture syntax
  (`name:expr`) or its `@skip` auto-splicing convenience -- both are
  Aether-specific authoring conveniences, not properties of the target
  formats -- so every assembled grammar is `@noskip` (whitespace
  tolerance has to already be written explicitly into the imported
  rules, matching how real ABNF/EBNF/PEG source is actually written),
  and an `Ichor.Actions` module written against one only ever sees the
  default fallback shape (`Ichor.Node`/passthrough), never a named
  capture.
  """

  alias Grammar.IR

  @type style :: :abnf | :bnf | :ebnf_iso | :peg

  @style_modules %{
    abnf: Ichor.ABNF,
    bnf: Ichor.BNF,
    ebnf_iso: Ichor.EBNF.ISO,
    peg: Ichor.PEG
  }

  @doc "The style names `import_grammar/3`/`Mix.Tasks.Ichor.Gen` accept, matched against `--style`/`@style`/a file extension."
  @spec styles() :: [style()]
  def styles, do: Map.keys(@style_modules)

  # RFC 5234 Appendix B.1's own core rules, in ABNF itself -- parsed via
  # Ichor.ABNF (already exists; no reason to hand-transcribe fifteen
  # Grammar.IR literals instead of just writing the RFC's own text and
  # importing it the normal way). CRLF line endings because abnf.aether's
  # own CRLF token requires them, same as
  # `Support.CrossFormat.read_abnf_source!/1` normalizes for real ABNF
  # fixture files.
  #
  # Deliberately parsed at *runtime* (the first time it's needed), not
  # baked in as a compile-time module attribute: `Ichor.ABNF.run/1` is
  # itself generated by `use Ichor` in a separate module, and calling it
  # from another module's own compile-time attribute evaluation is
  # exactly the kind of cross-module compile-time dependency Elixir's
  # compiler doesn't fully guarantee ordering for -- it was observed to
  # occasionally pick up a not-yet-fully-compiled `Ichor.ABNF.Actions`,
  # silently falling back to a bare `%Ichor.Node{}` per RFC-5234 rule
  # (`Ichor.Actions`'s own `FunctionClauseError` fallback, swallowed
  # rather than raised) instead of the real `Grammar.IR` ruleset. The
  # identical call always behaves correctly once made at ordinary
  # runtime, after both modules are actually fully loaded.
  @core_rules_abnf """
                   ALPHA  = %x41-5A / %x61-7A
                   BIT    = "0" / "1"
                   CHAR   = %x01-7F
                   CR     = %x0D
                   CRLF   = CR LF
                   CTL    = %x00-1F / %x7F
                   DIGIT  = %x30-39
                   DQUOTE = %x22
                   HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
                   HTAB   = %x09
                   LF     = %x0A
                   LWSP   = *(WSP / CRLF WSP)
                   OCTET  = %x00-FF
                   SP     = %x20
                   VCHAR  = %x21-7E
                   WSP    = SP / HTAB
                   """
                   |> String.replace("\r\n", "\n")
                   |> String.replace("\n", "\r\n")

  defp core_rules_abnf_ruleset do
    case Ichor.ABNF.run(@core_rules_abnf) do
      {:ok, ruleset} -> ruleset
    end
  end

  @doc """
  Imports `source` (written in `style`) into a runnable `%Aether.Grammar{}`.

  `opts`:

    * `:root` -- the entry rule's name (an atom; matched against the
      ruleset's own key casing -- e.g. `:foo`, never `:"Foo"`). Defaults
      to the first rule `source` itself declares.

  Returns `{:error, Ichor.Error.t()}` if `source` fails to parse, if it
  declares no rules at all and no `:root` override was given, or if an
  explicit `:root` names a rule the ruleset doesn't actually have.
  """
  @spec import_grammar(style(), String.t(), keyword()) ::
          {:ok, Aether.Grammar.t()} | {:error, Ichor.Error.t() | [Ichor.Error.t()]}
  def import_grammar(style, source, opts \\ []) when is_map_key(@style_modules, style) do
    source = normalize_line_endings(style, source)

    with {:ok, ruleset} <- run_importer(style, source),
         {:ok, order} <- rule_order(style, source) do
      ruleset = maybe_add_core_rules(style, ruleset)
      root = Keyword.get(opts, :root) || List.first(order)

      cond do
        is_nil(root) ->
          {:error, Ichor.Error.new(message: "#{style} source declares no rules", stage: :action)}

        not Map.has_key?(ruleset, root) ->
          {:error,
           Ichor.Error.new(
             message: "root #{inspect(root)} isn't a rule this #{style} source declares",
             stage: :action
           )}

        true ->
          {:ok, assemble(ruleset, root, [])}
      end
    end
  end

  defp run_importer(style, source), do: Map.fetch!(@style_modules, style).run(source)

  # RFC 5234's own CRLF token requires literal "\r\n" -- real ABNF
  # source (RFCs, specs) is technically supposed to have it, but is
  # near-universally saved/pasted with bare "\n" on a Unix system in
  # practice. Normalize first (undoing any CRLF already present) rather
  # than blindly appending "\r", or a file that already has real CRLFs
  # would end up with "\r\r\n".
  defp normalize_line_endings(:abnf, source),
    do: source |> String.replace("\r\n", "\n") |> String.replace("\n", "\r\n")

  defp normalize_line_endings(_style, source), do: source

  # Only the *transitive closure* of core rules the source actually
  # references, never all sixteen unconditionally -- Aether's tokenizer
  # is one global maximal-munch pass producing one token stream, so
  # blanket-merging every core rule regardless of use would add several
  # *overlapping* single-character tokens (CHAR's %x01-7F alone
  # contains DIGIT/ALPHA/CTL/...'s own ranges) that never appear in the
  # source at all. A tie in maximal munch is broken by declaration
  # order, not by "which rule actually wanted this token" -- so an
  # unreferenced, wider core rule like CHAR or OCTET happening to tie
  # (and win) against DIGIT on a digit character would silently break
  # every rule that specifically references DIGIT, since a token's name
  # has to match exactly (`Parser.match_token`), not just its shape.
  # Restricting to what's referenced avoids introducing that ambiguity
  # for a rule that was never going to use the wider one anyway; two
  # core rules that genuinely overlap *and* are both genuinely
  # referenced by the same source can still collide -- an inherent
  # limit of one shared token stream, not specific to this function.
  defp maybe_add_core_rules(:abnf, ruleset) do
    core_rules = core_rules_abnf_ruleset()
    core_names = MapSet.new(Map.keys(core_rules))

    referenced_core =
      ruleset
      |> Map.values()
      |> Enum.flat_map(&direct_refs/1)
      |> Ichor.Toolkit.Graph.reachable(fn name ->
        case Map.fetch(core_rules, name) do
          {:ok, ir} -> direct_refs(ir)
          :error -> []
        end
      end)
      |> MapSet.intersection(core_names)

    Map.merge(Map.take(core_rules, MapSet.to_list(referenced_core)), ruleset)
  end

  defp maybe_add_core_rules(_style, ruleset), do: ruleset

  defp direct_refs(%IR.RuleRef{name: name}), do: [name]
  defp direct_refs(%IR.Seq{exprs: exprs}), do: Enum.flat_map(exprs, &direct_refs/1)
  defp direct_refs(%IR.Choice{exprs: exprs}), do: Enum.flat_map(exprs, &direct_refs/1)
  defp direct_refs(%{expr: inner}), do: direct_refs(inner)
  defp direct_refs(_leaf), do: []

  # ---- rule declaration order --------------------------------------------
  #
  # Every importer's own `run/1` folds source order away into a plain
  # map (needed so a rule's own eventual name -- however it's cased --
  # can be looked up as an ordinary key, not so anyone could recover
  # declaration order from it afterward). `parse/1` -- already generated
  # by each importer's own `use Ichor`, no importer changes needed at
  # all -- returns the *raw*, unevaluated capture tree instead (an
  # `Ichor.Capture.raw_captures/0` ordered list, not a map), which still
  # has it: a `Star`/`Plus`-captured name arrives as a list in match
  # order (or, with exactly one occurrence, as a bare node --
  # `List.wrap/1` handles both uniformly).

  defp rule_order(:abnf, source) do
    with {:ok, _pos, raw_captures} <- Ichor.ABNF.parse(source) do
      names =
        raw_captures
        |> Keyword.get(:rule, [])
        |> List.wrap()
        |> Enum.map(fn {:rule, :rule, caps} ->
          {:token, :RULENAME, text} = Keyword.fetch!(caps, :RULENAME)
          text |> String.downcase() |> String.to_atom()
        end)

      {:ok, names}
    end
  end

  defp rule_order(:bnf, source) do
    with {:ok, _pos, raw_captures} <- Ichor.BNF.parse(source) do
      names =
        raw_captures
        |> Keyword.get(:rule, [])
        |> List.wrap()
        |> Enum.map(fn {:rule, :rule, caps} ->
          {:rule, :nonterminal, nonterm_caps} = Keyword.fetch!(caps, :nonterminal)
          {:token, :NONTERM_NAME, text} = Keyword.fetch!(nonterm_caps, :NONTERM_NAME)
          String.to_atom(text)
        end)

      {:ok, names}
    end
  end

  defp rule_order(:ebnf_iso, source) do
    with {:ok, _pos, raw_captures} <- Ichor.EBNF.ISO.parse(source) do
      names =
        raw_captures
        |> Keyword.get(:syntax_rule, [])
        |> List.wrap()
        |> Enum.map(fn {:rule, :syntax_rule, caps} ->
          {:rule, :meta_identifier, mi_caps} = Keyword.fetch!(caps, :meta_identifier)
          {:token, :IDENT, text} = Keyword.fetch!(mi_caps, :IDENT)
          text |> String.trim() |> String.to_atom()
        end)

      {:ok, names}
    end
  end

  defp rule_order(:peg, source) do
    with {:ok, _pos, raw_captures} <- Ichor.PEG.parse(source) do
      names =
        raw_captures
        |> Keyword.get(:rule, [])
        |> List.wrap()
        |> Enum.map(fn {:rule, :rule, caps} ->
          {:token, :IDENT, text} = Keyword.fetch!(caps, :IDENT)
          String.to_atom(text)
        end)

      {:ok, names}
    end
  end

  # ---- assembly -----------------------------------------------------------
  #
  # Promoted from Support.CrossFormat.assemble/3 (Ichor's own test
  # suite's cross-format equivalence fixture), which this now shares
  # rather than duplicates -- see that module for how it's exercised
  # against real ABNF/EBNF/PEG source today.

  @doc """
  Builds a grammar from `ruleset`, `root` (an atom naming the entry
  rule), and `token_names` (the subset of `ruleset` keys that are
  lexical/terminal -- everything else becomes a parser rule; `[]` is a
  perfectly good default, since every bare `Literal`/`CharClass`/`Any`
  leaf inside a designated *rule* still gets auto-promoted into its own
  synthetic token below, exactly as `Aether.Parser` already does for
  hand-written Aether source -- pre-declaring a name as a token only
  matters if you want it to read as one *by that name* in generated
  code, not for correctness). `@noskip` always -- see this module's own
  moduledoc for why.
  """
  @spec assemble(%{atom() => Grammar.IR.expr()}, atom(), [atom()]) :: Aether.Grammar.t()
  def assemble(ruleset, root, token_names) do
    token_set = MapSet.new(token_names)
    given_tokens = Map.take(ruleset, token_names)
    given_rules = Map.reject(ruleset, fn {name, _ir} -> MapSet.member?(token_set, name) end)

    {promoted_rules, anon_tokens} =
      Enum.map_reduce(given_rules, %{}, fn {name, ir}, anon_acc ->
        {ir2, anon_acc} = promote(ir, anon_acc)
        {{name, ir2}, anon_acc}
      end)

    anon_names = Enum.map(anon_tokens, fn {name, _ir} -> name end)

    %Aether.Grammar{
      name: "imported",
      root: root,
      skip: nil,
      case_insensitive: false,
      tokens: Map.merge(given_tokens, Map.new(anon_tokens)),
      token_order: token_names ++ anon_names,
      anon_tokens: MapSet.new(anon_names),
      rules: Map.new(promoted_rules)
    }
  end

  defp promote(%IR.Literal{} = leaf, anon_acc), do: promote_leaf(leaf, anon_acc)
  defp promote(%IR.CharClass{} = leaf, anon_acc), do: promote_leaf(leaf, anon_acc)
  defp promote(%IR.Any{} = leaf, anon_acc), do: promote_leaf(leaf, anon_acc)
  defp promote(%IR.RuleRef{} = ref, anon_acc), do: {ref, anon_acc}

  defp promote(%IR.Seq{exprs: exprs} = node, anon_acc) do
    {exprs2, anon_acc} = Enum.map_reduce(exprs, anon_acc, &promote/2)
    {%{node | exprs: exprs2}, anon_acc}
  end

  defp promote(%IR.Choice{exprs: exprs} = node, anon_acc) do
    {exprs2, anon_acc} = Enum.map_reduce(exprs, anon_acc, &promote/2)
    {%{node | exprs: exprs2}, anon_acc}
  end

  defp promote(%{expr: inner} = node, anon_acc) do
    {inner2, anon_acc} = promote(inner, anon_acc)
    {%{node | expr: inner2}, anon_acc}
  end

  defp promote_leaf(leaf, anon_acc) do
    stripped = strip(leaf)

    case Enum.find(anon_acc, fn {_name, existing} -> existing == stripped end) do
      {name, _existing} ->
        {IR.rule_ref(name), anon_acc}

      nil ->
        name = :"ANON_#{map_size(anon_acc)}"
        {IR.rule_ref(name), Map.put(anon_acc, name, stripped)}
    end
  end

  # Structural comparison for anon-token deduplication (two rules using
  # an identical literal shouldn't get two different synthetic tokens)
  # -- source-span metadata naturally differs even between structurally
  # identical leaves, so it has to be stripped first. A private copy of
  # `Support.IRStrip.strip/1` rather than a dependency on it: this is
  # `lib/`, `test/support/` isn't on its compile path.
  defp strip(%IR.Literal{value: v}), do: IR.literal(v)
  defp strip(%IR.CharClass{ranges: r}), do: IR.char_class(r)
  defp strip(%IR.Any{}), do: IR.any()
end
