defmodule Ichor.PEG do
  @moduledoc """
  The PEG front-end (Ford's paper, pest/PEG.js-style convention):
  `priv/grammar/peg.aether` parsed by Aether's own front-end, compiled
  by the native codegen backend (`use Ichor`), dispatching to
  `Ichor.PEG.Actions` (`Grammar.IR` as its target category).

  The `.aether` source lives under `priv/grammar/`, not `lib/`, for the
  same reason as `Ichor.ABNF`'s own: `use Ichor` only ever reads it
  once, at compile time.

      iex> {:ok, ruleset} = Ichor.PEG.run("digit  <- [0-9]\\nnumber <- digit+\\n")
      iex> ruleset[:number]
      %Grammar.IR.Plus{expr: %Grammar.IR.RuleRef{name: :digit}}

  `run/1` (generated by `use Ichor`) returns `{:ok, %{ident_atom =>
  Grammar.IR.expr()}}` for a whole `grammar_file` -- every rule the
  source defines. `parse/1` and `tokenize/1` (also generated) are
  available for a bare recognizer or raw token stream, with no
  `Ichor.PEG.Actions` involved.
  """

  use Ichor,
    grammar: "../../priv/grammar/peg.aether",
    actions: Ichor.PEG.Actions
end
