alpha char = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" ;
digit char = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
sp = " " | "\t" | ",";
ws = { sp } ;
symbol start = alpha char | "_" | "+" | "-" | "*" | "/" | "<" | ">" | "=" | "!" | "?" ;
symbol = symbol start, { symbol start | digit char } ;
keyword = ":", symbol ;
number = [ "-" ], digit char, { digit char }, [ ".", digit char, { digit char } ] ;
str char = alpha char | digit char | " " | "." | "," | "!" ;
string = '"', { str char }, '"' ;
atom = number | symbol | keyword | string ;
form = list | vec | map | quote sugar | quasiquote sugar | unquote splice sugar | unquote sugar | meta sugar | atom ;
list = "(", ws, { form, ws }, ")" ;
vec = "[", ws, { form, ws }, "]" ;
map = "{", ws, { form, ws, form, ws }, "}" ;
quote sugar = "'", ws, form ;
quasiquote sugar = "`", ws, form ;
unquote splice sugar = "~@", ws, form ;
unquote sugar = "~", ws, form ;
meta sugar = "^", ws, form, ws, form ;
