defmodule Ichor.EBNF.ISO do
  @moduledoc """
  The ISO/IEC 14977 EBNF front-end: `priv/grammar/ebnf-iso.aether`
  parsed by Aether's own front-end, compiled by the native codegen
  backend (`use Ichor`), dispatching to `Ichor.EBNF.ISO.Actions`
  (`Grammar.IR` as its target category).

  The `.aether` source lives under `priv/grammar/`, not `lib/`, for the
  same reason as `Ichor.ABNF`'s own: `use Ichor` only ever reads it
  once, at compile time.

      iex> {:ok, ruleset} = Ichor.EBNF.ISO.run("number = digit, { digit } ;\\n")
      iex> ruleset[:number]
      %Grammar.IR.Seq{exprs: [%Grammar.IR.RuleRef{name: :digit}, %Grammar.IR.Star{expr: %Grammar.IR.RuleRef{name: :digit}}]}

  `run/1` (generated by `use Ichor`) returns `{:ok, %{meta_identifier_atom
  => Grammar.IR.expr()}}` for a whole `syntax` -- every rule the source
  defines. `parse/1` and `tokenize/1` (also generated) are available
  for a bare recognizer or raw token stream, with no
  `Ichor.EBNF.ISO.Actions` involved.

  W3C-only syntax (`?`/`*`/`+` suffixes, `[...]` as a character class
  rather than ISO's own "optional", `::=`) fails informatively, not
  silently, when fed to this path: it's simply not valid ISO EBNF
  syntax, so `Aether.Parser` itself reports a normal,
  location-annotated `Ichor.Error` before `Ichor.EBNF.ISO.Actions` ever
  runs.
  """

  use Ichor,
    grammar: "../../../priv/grammar/ebnf-iso.aether",
    actions: Ichor.EBNF.ISO.Actions
end
