defmodule Ichor.EBNF.W3C do
  @moduledoc """
  The W3C-style EBNF front-end -- the notation the XML 1.0 spec's own
  section 6 "Notation" uses, also shared by XQuery/XPath's grammars:
  `priv/grammar/ebnf-w3c.aether` parsed by Aether's own front-end,
  compiled by the native codegen backend (`use Ichor`), dispatching to
  `Ichor.EBNF.W3C.Actions` (`Grammar.IR` as its target category).

  The `.aether` source lives under `priv/grammar/`, not `lib/`, for the
  same reason as `Ichor.ABNF`'s own: `use Ichor` only ever reads it
  once, at compile time.

      iex> {:ok, ruleset} = Ichor.EBNF.W3C.run("nonzero_digit ::= [0-9] - '0'\\n")
      iex> ruleset[:nonzero_digit]
      %Grammar.IR.Seq{exprs: [%Grammar.IR.NotPred{expr: %Grammar.IR.Literal{value: "0"}}, %Grammar.IR.CharClass{ranges: [{48, 57}]}]}

  `run/1` (generated by `use Ichor`) returns `{:ok, %{ident_atom =>
  Grammar.IR.expr()}}` for a whole `grammar_file` -- every rule the
  source defines. `parse/1` and `tokenize/1` (also generated) are
  available for a bare recognizer or raw token stream, with no
  `Ichor.EBNF.W3C.Actions` involved.
  """

  use Ichor,
    grammar: "../../../priv/grammar/ebnf-w3c.aether",
    actions: Ichor.EBNF.W3C.Actions
end
