defmodule Ichor.EBNF.W3C.ActionsTest do
  use ExUnit.Case, async: true
  doctest Ichor.EBNF.W3C

  alias Grammar.IR
  alias Support.IRStrip

  defp run(source), do: Ichor.EBNF.W3C.run(source)

  defp rule(source, name) do
    {:ok, ruleset} = run(source)
    Map.fetch!(ruleset, name)
  end

  describe "the W3C EBNF worked example" do
    test "namechar: a char class merged across three adjacent ranges" do
      assert IRStrip.strip(rule("namechar ::= [a-zA-Z0-9] | '-' | '.'\n", :namechar)) ==
               IRStrip.strip(
                 IR.choice([
                   IR.char_class([{?a, ?z}, {?A, ?Z}, {?0, ?9}]),
                   IR.literal("-"),
                   IR.literal(".")
                 ])
               )
    end

    test "nonzero_digit: the exception operator (best-effort, see moduledoc)" do
      assert IRStrip.strip(rule("nonzero_digit ::= [0-9] - '0'\n", :nonzero_digit)) ==
               IRStrip.strip(IR.seq([IR.not_pred(IR.literal("0")), IR.char_class([{?0, ?9}])]))
    end
  end

  describe "terminals" do
    test "single- and double-quoted literals" do
      assert IRStrip.strip(rule(~S[a ::= 'x' "y"], :a)) ==
               IRStrip.strip(IR.seq([IR.literal("x"), IR.literal("y")]))
    end
  end

  describe "quantifiers ?/*/+ (near-transliterations of Aether's own)" do
    test "all three in one sequence" do
      assert IRStrip.strip(rule("a ::= 'x'? 'y'* 'z'+\n", :a)) ==
               IRStrip.strip(
                 IR.seq([
                   IR.opt(IR.literal("x")),
                   IR.star(IR.literal("y")),
                   IR.plus(IR.literal("z"))
                 ])
               )
    end
  end

  describe "grouping" do
    test "(...) groups without changing meaning" do
      assert IRStrip.strip(rule("a ::= ('x' | 'y') 'z'\n", :a)) ==
               IRStrip.strip(
                 IR.seq([IR.choice([IR.literal("x"), IR.literal("y")]), IR.literal("z")])
               )
    end
  end

  describe "hex_ref (#xN, standalone)" do
    test "a single character reference" do
      assert IRStrip.strip(rule("a ::= #x41\n", :a)) == IRStrip.strip(IR.literal("A"))
    end
  end

  describe "char_class (the real finding: folded into one token, see moduledoc)" do
    test "a single range" do
      assert IRStrip.strip(rule("a ::= [a-z]\n", :a)) == IRStrip.strip(IR.char_class([{?a, ?z}]))
    end

    test "adjacent ranges with no separator (a-zA-Z0-9) stay distinct" do
      assert IRStrip.strip(rule("a ::= [a-zA-Z0-9]\n", :a)) ==
               IRStrip.strip(IR.char_class([{?a, ?z}, {?A, ?Z}, {?0, ?9}]))
    end

    test "a bare character alongside a range" do
      assert IRStrip.strip(rule("a ::= [a-z0]\n", :a)) ==
               IRStrip.strip(IR.char_class([{?a, ?z}, {?0, ?0}]))
    end

    test "hex_ref endpoints inside a range" do
      assert IRStrip.strip(rule("a ::= [#x41-#x5A]\n", :a)) ==
               IRStrip.strip(IR.char_class([{0x41, 0x5A}]))
    end

    test "negation (^)" do
      assert IRStrip.strip(rule("a ::= [^a-z]\n", :a)) ==
               IRStrip.strip(IR.seq([IR.not_pred(IR.char_class([{?a, ?z}])), IR.any()]))
    end
  end

  describe "rule references" do
    test "a bare IDENT in primary position references another rule" do
      assert IRStrip.strip(rule("a ::= b\n", :a)) == IRStrip.strip(IR.rule_ref(:b))
    end
  end

  describe "comments and multiple rules" do
    test "a leading comment doesn't break parsing" do
      source = "/* leading */\na ::= 'x'\n"
      assert {:ok, ruleset} = run(source)
      assert IRStrip.strip(ruleset[:a]) == IRStrip.strip(IR.literal("x"))
    end

    test "two consecutive rules stay separate (the other real finding, see priv/grammar/ebnf-w3c.aether)" do
      source = "a ::= 'x'\nb ::= a\n"
      assert {:ok, ruleset} = run(source)
      assert IRStrip.strip(ruleset[:a]) == IRStrip.strip(IR.literal("x"))
      assert IRStrip.strip(ruleset[:b]) == IRStrip.strip(IR.rule_ref(:a))
    end

    test "a trailing newline (or lack of one) doesn't affect the result" do
      assert {:ok, with_nl} = run("a ::= 'x'\n")
      assert {:ok, without_nl} = run("a ::= 'x'")
      assert IRStrip.strip(with_nl[:a]) == IRStrip.strip(without_nl[:a])
    end
  end

  describe "duplicate definitions" do
    test "defining the same rule twice is a real error" do
      source = "a ::= 'x'\na ::= 'y'\n"
      assert {:error, %Ichor.Error{message: message}} = run(source)
      assert message =~ "defined more than once"
    end
  end

  describe "parse/1 and tokenize/1 (bare recognizer, generated by use Ichor)" do
    test "parse/1 matches with no Ichor.EBNF.W3C.Actions involved" do
      assert {:ok, _pos, _raw_captures} = Ichor.EBNF.W3C.parse("a ::= 'x'\n")
    end

    test "tokenize/1 exposes the raw token stream, including a whole char class as one token" do
      assert {:ok, tokens} = Ichor.EBNF.W3C.tokenize("a ::= [a-z]\n")

      assert Enum.map(tokens, & &1.name) == [
               :IDENT,
               :TRIVIA,
               :DEFINED_AS,
               :TRIVIA,
               :CHAR_CLASS,
               :NEWLINE
             ]
    end
  end
end
