lookahead pos   = "(?=" ;
lookahead neg   = "(?!" ;
shorthand class = "\", ( "d" | "w" | "s" | "D" | "W" | "S" ) ;
escaped char    = "\", ( "." | "[" | "]" | "^" | "-" | "*" | "+" | "?" | "|" | "(" | ")" | "{" | "}" | "\" | "/" | "d" | "w" | "s" | "D" | "W" | "S" | "n" | "r" | "t" ) ;
literal char    = " " | "!" | '"' | "#" | "$" | "%" | "&" | "'"
                | "-"
                | "/" | "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | ":" | ";" | "<" | "=" | ">"
                | "@" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
                | "_" | "`"
                | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
                | "~" ;

pattern     = alternative, { "|", alternative } ;
alternative = { term } ;
term        = atom, [ quantifier ] ;
quantifier  = "*" | "+" | "?" | bound ;
bound       = "{", literal char, { literal char }, [ ",", { literal char } ], "}" ;
atom        = group | char class | "." | shorthand class | escaped char | literal char ;
group       = ( lookahead pos | lookahead neg | "(" ), pattern, ")" ;
char class  = "[", [ "^" ], class item, { class item }, "]" ;
class item  = range | class atom ;
range       = class atom, "-", class atom ;
class atom  = escaped char | literal char ;
